version: '3.9'

services:
  frontend:
    image: techtest/frontend:latest
    ports:
      - 80:80
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    image: techtest/backend:latest
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - DB_HOST=database.example.com
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydatabase
    networks:
      - react-express

  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - react-express

volumes:
  postgres-data:

networks:
  react-express:
